### ISSUE TITLE
cli option for timeout

### ISSUE THREAD

**Issue by jgysel** [zpeters/speedtest#100]
Would be nice to have a command line option to specify the max time to wait:

```
# speedtest
github.com/zpeters/speedtest -- unofficial cli for speedtest.net
Server: 2629 - Sydney (Telstra)
2017/04/24 10:17:55 Testing download speed
.........2017/04/24 10:18:48 net/http: request canceled (Client.Timeout exceeded while reading body)
```

By the way, many thanks for this great tool!

**Comment by gibsonblood** [comment]
Yes, thank you for this tool! Very useful.

Is there any way to escalate this? I understand development isn't too regular anymore. Test fails in certain locations and I would like to use this tool in those location.

**Comment by zpeters** [comment]
yep i can look at this.  I will see if i can take a peek tonight.

**Comment by zpeters** [comment]
I think i might have a fix for you on the development branch.  Seems to work.  Will compile the binaries adn get them released later on today

**Comment by gibsonblood** [comment]
Great, thanks! I'll test it out.

**Comment by zpeters** [comment]
just released binaries.  have a look and let me know waht you think

**Comment by gibsonblood** [comment]
It's working so far! Thanks!
I'll let you know if I am still encountering issues.

**Comment by zpeters** [comment]
💯 👍 👍 👍
