### ISSUE TITLE
Speetest Syntax ignored when path variable is used

### ISSUE THREAD

**Issue by Elrick91** [zpeters/speedtest#101]
Hi,

For unknow reason, when i use variable in path to execute Speetest, it ignore all syntax (-s -a ....)
I use Windows 10 x64 with SpeedTest x64.

I paste you a screenshot copy to show issue :

- first test, the command directly with parameters
- the second, same as first, with path variable behind ... parameters are **not taken !!!**

<a target="_blank" href="http://www.hostingpics.net" title="Hebergeur d'image"><img src="https://img4.hostingpics.net/pics/640303BugwithSpeedTestcommandline2.jpg" border="0" alt="Hebergeur d'image" /></a>

Workaround : i use CD /d %myvariable% to be into the directory and execute the speedtest instruction directly in the next line of my code.

Is it possible to fix it please ?

Best Regards,

Elrick

**Comment by zpeters** [comment]
Somehow this one escaped me.  Just saw it on the issue tracker.  I will look into this

**Comment by zpeters** [comment]
COMING SOON
=============
This version of speedtest is not supported.  The underlying method of speed testing is not (and has not) been reliable.  There is a new version of the speedtest protocol that i am actively working on a rewrite for. Expected release date is September 2018

**Comment by zpeters** [comment]
Initial testing release of v2.0 is out for the testing. See "releases" for downloads.  The current "test" is hard coded and there are no options at the moment.  I believe we'll end up needing a "tuning" to adjust the size and amount of data based on your internet connection.  Please send me any feedback at zpeters@gmail.com or through the issues

**Comment by zpeters** [comment]
Marking this as closed.  Thank you for the help @harrywhite4
