### ISSUE TITLE
arm版本在网件R6300V2梅林固件运行报Illegal instruction

### ISSUE THREAD

**Issue by zxq1002** [zpeters/speedtest#109]
**Describe the bug**
arm版本在qnap ts-231+上运行没问题，但网件R6300V2梅林固件运行提示Illegal instruction
cpu都是arm架构

**To Reproduce**
download and run it.

**Expected behavior**

**Screenshots**
zhouxq@NETGEAR-A787:/tmp/home/root# ./speedtest-go 
Illegal instruction

**Router (please complete the following information):**
 - OS: meilin
 - Version: v1.0.5

**Additional context**
no more.

**Comment by zpeters** [comment]
I will accept patches but i'm not actively maintaining this software.  If you have a way for me to get access to this or a similar device i might be able to help.
