### ISSUE TITLE
Speedtest when 1 server Times out

### ISSUE THREAD

**Issue by Norava** [zpeters/speedtest#112]
When running a Speedtest from a server in Reporting mode having issues pulling a test when AT&T Node is hit and the Error: Get http://mobspeedtest002.npm.mobile.att.net/speedtest/latency.txt: net/http: request canceled while waiting for connection (Client.Timeout exceeded
 while awaiting headers) appears.

When running in  debugging mode, 2 other servers ARE found but test cancels because it fails on this 1:
PS C:\Windows\system32> .\Speedtest.exe -r -d 
2018/08/21 15:24:55 Env Report
2018/08/21 15:24:55 -------------------------------
2018/08/21 15:24:55 [User Environment]
2018/08/21 15:24:55 Arch: 386
2018/08/21 15:24:55 OS: windows
2018/08/21 15:24:55 IP: 12.34.243.194
2018/08/21 15:24:55 Lat: 33.2747
2018/08/21 15:24:55 Lon: -96.5532
2018/08/21 15:24:55 ISP: AT&T Enterprise
2018/08/21 15:24:55 Config: http://c.speedtest.net/speedtest-config.php?x=mP6EAAzpnkkh5fiQ
2018/08/21 15:24:55 Servers: http://c.speedtest.net/speedtest-servers-static.php?x=c3XlCTXiDjZCcHlf
2018/08/21 15:24:55 User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.21 Safari/537.36
2018/08/21 15:24:55 HTTP Timeout (seconds): 15
2018/08/21 15:24:55 -------------------------------
2018/08/21 15:24:55 [args]
2018/08/21 15:24:55 []string{"C:\\Windows\\system32\\Speedtest.exe", "-r", "-d"}
2018/08/21 15:24:55 --------------------------------
2018/08/21 15:24:55 Getting all servers for our test list
2018/08/21 15:24:56 Getting closest servers...
2018/08/21 15:24:56 Sorting all servers by distance...
2018/08/21 15:24:56 Getting the fastests of our closest servers...
2018/08/21 15:24:56 Doing 3 runs of {http://ttn.speedtest.t-mobile.com/speedtest/upload.jsp 33.0503 -96.7458 Plano, TX United States US T-Mobile 12688 30.73357624597958 
0}
2018/08/21 15:24:56 Testing latency: Plano, TX (T-Mobile)
2018/08/21 15:24:56 	Run took: 96.0006ms
2018/08/21 15:24:56 Testing latency: Plano, TX (T-Mobile)
2018/08/21 15:24:56 	Run took: 46.9979ms
2018/08/21 15:24:56 Testing latency: Plano, TX (T-Mobile)
2018/08/21 15:24:56 	Run took: 19.0028ms
2018/08/21 15:24:56 Testing latency: Plano, TX (T-Mobile)
2018/08/21 15:24:56 	Run took: 19.0009ms
2018/08/21 15:24:56 Testing latency: Plano, TX (T-Mobile)
2018/08/21 15:24:56 	Run took: 77.9981ms
2018/08/21 15:24:56 Total runs took: 19.0009
2018/08/21 15:24:56 Server latency was ok 19.000900 adding to successful servers list
2018/08/21 15:24:56 Doing 3 runs of {http://mobspeedtest002.npm.mobile.att.net/speedtest/upload.php 33.02 -96.69 Plano, TX United States US AT&T Wireless 18375 31.062039
722414987 0}
2018/08/21 15:24:56 Testing latency: Plano, TX (AT&T Wireless)
2018/08/21 15:25:11 Get http://mobspeedtest002.npm.mobile.att.net/speedtest/latency.txt: net/http: request canceled while waiting for connection (Client.Timeout exceeded
 while awaiting headers)

PS C:\Windows\system32>

**Comment by zpeters** [comment]
COMING SOON
=============
This version of speedtest is not supported.  The underlying method of speed testing is not (and has not) been reliable.  There is a new version of the speedtest protocol that i am actively working on a rewrite for. Expected release date is September 2018

**Comment by zpeters** [comment]
Initial testing release of v2.0 is out for the testing. See "releases" for downloads.  The current "test" is hard coded and there are no options at the moment.  I believe we'll end up needing a "tuning" to adjust the size and amount of data based on your internet connection.  Please send me any feedback at zpeters@gmail.com or through the issues
