### ISSUE TITLE
Inaccurate results after first execution...

### ISSUE THREAD

**Issue by larray** [zpeters/speedtest#20]
I REALLY like the idea of this tool, I've been looking for a way to keep Comcast honest.  After I thought I had the config correct and created a scheduled task on Windows... I kept getting odd results for the download speed.  It wasn't until I changed to another server that I got the right result again.  Example:

C:\>C:\temp\SpeedTest\speedtest-64-v0.07.2-xcompile.exe -s 3165
3165 | Georgia Institute of Technology (Atlanta, GA, United States)
Testing latency...
2015/04/03 18:07:28 Testing download speed
.........
2015/04/03 18:07:49 Testing upload speed
.....
Ping: 96.81 ms | Download: 42.09 Mbps | Upload: 10.37 Mbps

C:\>C:\temp\SpeedTest\speedtest-64-v0.07.2-xcompile.exe -s 3165
3165 | Georgia Institute of Technology (Atlanta, GA, United States)
Testing latency...
2015/04/03 18:09:37 Testing download speed
.........
2015/04/03 18:09:45 Testing upload speed
.....
Ping: 23.80 ms | Download: 574.53 Mbps | Upload: 10.72 Mbps

*** Changing to another server, then changing back doesn't seem to fix the issue.  Example - I previously used server 5027 | AT&T (Tucker, GA, United States), and I am still getting erroneous results even after trying server 3165.  The download speed doesn't even seem to be a factor off (like 10x).  Changing to another server I get the same affect - first works, second doesn't:
C:\>C:\temp\SpeedTest\speedtest-64-v0.07.2-xcompile.exe -s 1767
1767 | Comcast (Atlanta, GA, United States)
Testing latency...
2015/04/03 18:15:40 Testing download speed
.........
2015/04/03 18:16:07 Testing upload speed
.....
Ping: 47.40 ms | Download: 35.67 Mbps | Upload: 11.56 Mbps

C:\>C:\temp\SpeedTest\speedtest-64-v0.07.2-xcompile.exe -s 1767
1767 | Comcast (Atlanta, GA, United States)
Testing latency...
2015/04/03 18:16:19 Testing download speed
.........
2015/04/03 18:16:29 Testing upload speed
.....
Ping: 20.20 ms | Download: 621.10 Mbps | Upload: 11.53 Mbps

Its almost like the random data it should be downloading isn't random anymore and is getting cached.... which led me to check and in fact, if I turn off my web cache in my router, the speeds return to normal.... so methinks I need to put a rule into my router unless you can have the tool download random data like testmy.net.  ;)  Thanks!

**Comment by zpeters** [comment]
Thanks for the submission.  Looking into this this weekend

**Comment by larray** [comment]
Glad to help... know nothing about coding beyond some Powershell hacks, otherwise I'd pitch a fix.  I did confirm it is a caching issue.  For servers 5027,3165,1767 I traced the URL used for testing, placed exceptions in my firewall to not cache for calls to those sites so I've worked around the problem locally.  However it doesn't address the issue at large - how does testmy.net work around the issue by pulling randomized data?  IIRC - I had to put some blocking rules in place for speedtest.net and the comcast speed test site to prevent skewing the numbers as well a year or two ago.

**Comment by zpeters** [comment]
I looked over the code tonight and i'm not sure if there is a good way to work our your specific issue.

The way we test download speeds is based on who speedtest mini does their test, which is to download a "random" binary file of a range of sizes.  What this ends up being is just a jpg of random noise, just to fill up a predefined file size.

I don't like how they do this but for now the only way i can think to test download speeds without setting up my own hosted service is to piggyback on their method of downloading a "random" file.

I'm curious though since i haven't run across anyone reporting a caching server. Are you aware of any ways to tell the server to not cache specific requests?  I wonder if there is a special format to the http get or some other method to signal to the cache that we want a fresh version of this file and not a cache?  In the ideal world you'd have a "blob" of data being downloaded that is actually random and changes each time you download so it's not cached.

Let me know what you think or if you have any ideas on this.

**Comment by zpeters** [comment]
I might have figured something out.  It looks like there is a "client side" caching preference that can be set.  Building up a test compile for you if you'd be so kind as to test this out since i don't have a cache on my side.

URL in a few minutes...

**Comment by zpeters** [comment]
Okay should be some new binaries here with caching turned off for all requests.

http://media.thehelpfulhacker.net/index.php?dir=speedtest/v0.07.4/

**Comment by larray** [comment]
That appears to have done the trick!  Repeated attempts to the same server after the caching filter is turned off results in comparable results rather consistently.  (Within 10% - probably due to other users on my network - no where near the widely fluctuating values I was seeing before.)  The second, third and consecutive tests seem to be a little slower... but I will have to test over several hours to see if that is just my bias.  

The router/caching server I use is Astaro/Sophos UTM (there is a 50 user home license that is free - fabulous product).  I can tweak the caching rules and have done so for explicit speedtest.net calls - if I knew the right "pattern" in regex I could probably avoid this issue :)  Instead I figured out the URLs and put a block in for them.  Works, but you have to know to look for it and you might not always be at a site where the admin is willing or competent :)

Thanks very much for looking into this!
Andy
