### ISSUE TITLE
[request] option for down-/upstream only

### ISSUE THREAD

**Issue by Tsunayoshi** [zpeters/speedtest#28]
Hello,
i am using your speedtest to messure my internetspeed (obvious) and hand it's output over to nagios (a monitoring system).
From time to time my uploadtest takes really long (my provider isn't really qualified sometimes...), so the nagios client will give back a timeout, but at this point the download speedtest was already done and I am loosing this number. Also the nagios will do a quicker recheck and this causes an unnecessary load.

At this point i am getting a critial mail from my nagios system and can't see why.
I like to split the messure of up- and download in two commands. So I can change notification time and recheck times differently.

Is there a way you could implement this?

**Comment by zpeters** [comment]
This shouldn't be too difficult to implement.  Let me see what i can do.

**Comment by zpeters** [comment]
All set.  Updated version is available here: https://github.com/zpeters/speedtest/releases/tag/v0.8.1 or at the mirror here: http://media.thehelpfulhacker.net/index.php?dir=speedtest/v0.8.1/

**Comment by Tsunayoshi** [comment]
Thank you a lot!!
