### ISSUE TITLE
out of memory in embedded devices

### ISSUE THREAD

**Issue by jannson** [zpeters/speedtest#36]
I compile and run it in my RT-AC68U router (2 core ARM, 256M ram), than It got out of memory:

admin@RT-AC68U-7DB0:/tmp/home/root# /tmp/mnt/sda1/asus/speedtest 
github.com/zpeters/speedtest -- unofficial cli for speedtest.net
2015/08/10 10:43:10 Testing download speed
.......fatal error: runtime: out of memory

What can I do, if i want to reduce the memory of this program used.

**Comment by zpeters** [comment]
Thank you.  I will take a look into this.  In the meantime could you do this same run as "speedtest -d" and attach all of the debugging output.  This will help in troubleshooting.

Thanks,

**Comment by jannson** [comment]
At sthttp.go line: 324, use 
func respBodyLen(resp *http.Response) int {
	l := 0
	buf := make([]byte, 4096)
	for {
		if n, err := resp.Body.Read(buf); err != nil {
			break
		} else {
			l += n
		}
	}

	return l
}

Instead of 
 data, err := ioutil.ReadAll
len(data)
It looks no good, but now it works.

**Comment by zpeters** [comment]
Would you like to submit a pull request with your patch?

**Comment by jannson** [comment]
Sorry, I don't know how to send a pull request attaching this issue, so I put the url hear:
https://github.com/zpeters/speedtest/pull/37

**Comment by zpeters** [comment]
No worries I will check this out tomorrow. Thank you!

**Comment by zpeters** [comment]
Manually merged pull request.  Thank you!
