### ISSUE TITLE
speedtest-config.php and speedtest-servers-static.php blank

### ISSUE THREAD

**Issue by si458** [zpeters/speedtest#39]
when loading speedtest-config.php or speedtest-servers-static.php is shows a blank page

but after debugging speedtest.net, it appears you need to load the page with the extra variable of x=RANDOMNUMBER

e.g: http://c.speedtest.net/speedtest-config.php?x=1442587869539
e.g: http://c.speedtest.net/speedtest-servers-static.php?x=1442587869539

or load from these urls without the x variable:
https://www.speedtest.net/speedtest-config.php
https://www.speedtest.net/speedtest-servers-static.php

**Comment by zpeters** [comment]
Thank you, i will look at this right away...

**Comment by zpeters** [comment]
I did some quick testing and i'm not able to replicate. Curious if you are behind a firewall or some other device that is filtering your traffic.  When i hit http://c.speedtest.net/speedtest-config.php or http://c.speedtest.net/speedtest-servers-static.php with and without the "X" variable i am able to see the expected page.

It won't hurt anything that i can tell for me to add the "?x=12345" so i can do that to work around the issue, just curious what is causing this

**Comment by zpeters** [comment]
Alright i've made a release with your suggestions v0.8.4-a please test this out and let me know if it works for you.

Thank you!

**Comment by si458** [comment]
Wonderful! it works fine now
this issue only happened on one of our computers running Windows XP, our 7 and 8.1 machines are fine

**Comment by zpeters** [comment]
No problem!
