### ISSUE TITLE
create 32bit linux release

### ISSUE THREAD

**Issue by si458** [zpeters/speedtest#40]
Create a 32bit linux release as you have only made a 64bit version :)

**Comment by zpeters** [comment]
No problem.  I thought all the Linux guys were only 64 bit these days.  What are you running on 32 bit?

**Comment by si458** [comment]
I'm only running a simple centos 6 file server which only has 1gb ram so didn't see a point using 64bit

**Comment by zpeters** [comment]
Cool, i'll get something up in the next day or so.  I haven't tested in
environments with < 2gigs yet so if you notice any memory issues let me
know.

**Comment by zpeters** [comment]
Here you go..
https://github.com/zpeters/speedtest/releases/tag/v0.8.4-b
