### ISSUE TITLE
Running without any command line switches should output which server was selected for the test.

### ISSUE THREAD

**Issue by nemchik** [zpeters/speedtest#42]
I noticed if I run the exe (0.8.4-b) with no command line switches the output does not tell me which server is selected for the speedtest. If I run with the -s switch the output is the same but does include the server, but then I have to specify which server to use. I think it would make sense for the output without command line switches to include the server selected for the test.

**Comment by zpeters** [comment]
This is a simple slip up that I will fix

**Comment by nemchik** [comment]
Awesome, thanks! And thank you for your hard work on this program.

**Comment by zpeters** [comment]
All set!

Code is updated to v0.8.4-c with the recommended changes

http://media.thehelpfulhacker.net/index.php?dir=speedtest/v0.8.4-c/

or

https://github.com/zpeters/speedtest/releases/tag/v0.8.4-c

Enjoy!
