### ISSUE TITLE
line separator

### ISSUE THREAD

**Issue by eocula** [zpeters/speedtest#43]
Hi,

I'm trying to use speedtest to analyse my internet-bandwidth over a longer period of time. So I'm using the tool through a Windows-schedule, in command-line mode. The output is put in a output text-file.

I'm trying to use the output-file with a visualisation-tool. 

The problem I have is that the lines in the output-file are not separated by a <CR><LF> (As in a normal text-file). But by <LF><LF>

Is there any way of having that changed ?

Many thanks

Eddy

**Comment by zpeters** [comment]
I don't think I fully understand your question here.  The first part i understand that you want to gather speed test results repeatedly over time and save to a file for later analysis.  Can you give an example of what the current format is and then an example of what you would like it to look like?

Thank you

**Comment by eocula** [comment]
Hoi Zach,

 

First of all, thanks for contacting me by mail !

 

This is a screenshot, from Notepad++, of the first line of the output file :

 



 

 

The problematic characters are 

 

-       the <LF> character in the first line. Due to this, the tool I’m using the analyze the data is confused, and does not recognize the data-fields separated by “|” . So I have to delete that one manually before I start my analysis. In fact , the first line should contain the first line of test-results-data



-       The <LF> after  each data-line



-       The <LF> (only) character  at the end of each line. If you just make a text-file with Notepad with 2 “normal” lines, you’ll see a <CR><LF> combination when you open it with Notepad++. This is an example :





 

How the file would be best, is shown in below example , after  I have edited it, and deleted  :

 



 

 

In fact the <CR> is not absolutely necessary for me, but it would be better that the <LF> would be replaced by <CR><LF>

 

Hope this will help !

Regards,

Eddy

**Comment by zpeters** [comment]
It doesn't look like the screenshot came through.  Can you post it to imgur and send a link?  Thank you!

**Comment by eocula** [comment]
Hi Zach,

 

I have uploaded the picture to imgur   :

 

http://imgur.com/j9TrwGe

 

Regards,

Eddy

**Comment by zpeters** [comment]
@eocula i just released a new version that might fix this issue.  Would you mind testing it out?  This is for issue #41 

https://github.com/zpeters/speedtest/releases/tag/v0.8.4-d

**Comment by eocula** [comment]
Hi Zach,

 

This looks good now . See the last 3 line sin below screenshot. The lines are written with the version I had just downloaded :

 



 

Thanks a lot !

 

Hopefully you’ll find also something on the “high values” on the upload-speed (see my other mail)

Groeten,

Eddy

**Comment by zpeters** [comment]
Issue closed and moving on!
