### ISSUE TITLE
Sometimes very high values for Upload-speed

### ISSUE THREAD

**Issue by eocula** [zpeters/speedtest#44]
I'm running this tool now every 15 minutes since about 2 months. Mostly my upload-speeds are between  2043 and 3520 (about 1850 runs of the command-file).

However, I have around 450 entries with upload-speeds between  268435 and 805306 kbps. For me these upload-speeds are impossible.

Any idea what can be done on this ?

**Comment by polyzen** [comment]
+1

**Comment by eocula** [comment]
Dear polyzen,

Sorry but I do not understand your answer. What do you mean exactly ?

**Comment by polyzen** [comment]
This also happens when I use it. Arch Linux is the system I'm running it on

**Comment by zpeters** [comment]
I'll need a little more info to look into this.  Is it possible to run and log using the "-d" debugging switch and try to catch it in the act.

Thanks

**Comment by polyzen** [comment]
@zpeters, https://ptpb.pw/IcFw

**Comment by eocula** [comment]
OK, I will do this later today

 

Groeten,

Eddy

**Comment by eocula** [comment]
Hi,

 

I have setup a new schedule, now executing it with only the “-r” option, but also with the “-d” option.

 

Maybe accidently , but form the first run, it returns the high-value : 402653  . 

 

See attached result-file (Copy of speedtest_results_debug.txt). As you can see it ran at 12:50 CET

 

I’m attaching the output-file of the normal schedules as well. File : speedtest_results.txt

 

I did not noticed it before but I now see that almost all the lines  are containing high-values. Only a few lines have “reasonable looking values”. Note that in September, when I started the test, all upload-values were looking good.

 

Groeten,

Eddy

 

From: Eddy (LGC) [mailto:eddy.ocula@lagrandecense.be] 
Sent: Wednesday, November 11, 2015 08:02
To: 'zpeters/speedtest'; 'zpeters/speedtest'
Cc: 'Eddy (LGC)'
Subject: RE: [speedtest] Sometimes very high values for Upload-speed (#44)

 

OK, I will do this later today

 

Groeten,

Eddy

**Comment by eocula** [comment]
One thing more.

 

I just noticed about all upload-values of the last days are or 402653 or 805306. Were 805306 is exact the double value of 402653 :

 

 



 

Hopefully this helps you with finding the reason in the code. And a solution J

 

Regards,

Eddy

 

From: Eddy (LGC) [mailto:eddy.ocula@lagrandecense.be] 
Sent: Wednesday, November 11, 2015 13:01
To: 'zpeters/speedtest'; 'zpeters/speedtest'
Cc: 'Eddy (LGC)'
Subject: RE: [speedtest] Sometimes very high values for Upload-speed (#44)

 

Hi,

 

I have setup a new schedule, now executing it with only the “-r” option, but also with the “-d” option.

 

Maybe accidently , but form the first run, it returns the high-value : 402653  . 

 

See attached result-file (Copy of speedtest_results_debug.txt). As you can see it ran at 12:50 CET

 

I’m attaching the output-file of the normal schedules as well. File : speedtest_results.txt

 

I did not noticed it before but I now see that almost all the lines  are containing high-values. Only a few lines have “reasonable looking values”. Note that in September, when I started the test, all upload-values were looking good.

 

Groeten,

Eddy

 

From: Eddy (LGC) [mailto:eddy.ocula@lagrandecense.be] 
Sent: Wednesday, November 11, 2015 08:02
To: 'zpeters/speedtest'; 'zpeters/speedtest'
Cc: 'Eddy (LGC)'
Subject: RE: [speedtest] Sometimes very high values for Upload-speed (#44)

 

OK, I will do this later today

 

Groeten,

Eddy

**Comment by zpeters** [comment]
Thank you @eocula and @polyzen 

I can see from your examples what you are explaining.  I'm going to try to look into it this weekend and see what I can find out.

Cheers

**Comment by zpeters** [comment]
I just put out a debug release that will add some extra info to the upload process.  Would you mind running this with the "-d --uo" switches (-d = debugging, --uo = upload only) a few times and we'll see if we can catch this in the act again.

http://media.thehelpfulhacker.net/index.php?dir=speedtest/v0.8.4-d-1-ga02d067/

Thank you!

**Comment by polyzen** [comment]
https://ptpb.pw/YhJJ

**Comment by eocula** [comment]
I saw through the issue that “Daniel M. Capella” had sent you a results-file. 

 

Attached is my result-file. I ran it 3 times

 

 

 

Groeten,

Eddy

**Comment by zpeters** [comment]
Some how i am not receiving the attachments.  Could you possibly send them
to "zpeters@gmail.com"?

Thank you

**Comment by zpeters** [comment]
Merging work with #46 .  Also see #45 for info on binary protocol that will help with this.
