### ISSUE TITLE
Version 2.0 Planning

### ISSUE THREAD

**Issue by zpeters** [zpeters/speedtest#45]
Feedback from colin@zonion.org

https://github.com/zpeters/speedtest
Is very neat and certainly is in the spirit of https://github.com/sivel/speedtest-cli

Though I find that neither are super-reliable above a few hundred Mbps. Likely because they do not sustain a transfer for more than a second. (Ookla will transfer for 10s or more even on connections of 500Mbps and above).

Ookla uses a custom server and claim this allows better tests in excess of 200Mbps
(See http://www.ookla.com/support/a22990987/NetGauge-HTTP-Legacy-Fallback)
Client is flash (unless on mobile).

Though not described, the new test protocol does not look too complicated (though huge disclaimer, I have not figured the ins and outs of it).

Attached are some captures of testing on an 80Mbps connection (only download phase).
- Speedtest starts 15 TCP streams bt client and testserver over course of test.
- First starts at 8.2s, next 3 start 0.6s later, next 8 start 0.6s later
  - First may be test stream
  - Or may simply space out each connection start
- All connections terminate at roughly same time -- 10s after first stream started
  Inline image 2

Most streams look like format:
HI
HELLO 2.2 2014-06-01.01
DOWNLOAD 729604
DOWNLOAD JABCDEF...

The first stream started has a slightly different format:
HI
HELLO 2.2 2014-06-01.01
PING 1441239250094
PONG 1441239250175
PING 1441239250104
PONG 1441239250188
PING 1441239250167
PONG 1441239250250
PING 1441239250178
PONG 1441239250258
PING 1441239250231
...
HI
HELLO 2.2 2014-06-01.01
DOWNLOAD 1000000
DOWNLOAD JABCDEF...

Ping-pong timestamp is correct unix time including milliseconds.

Observations
- Once the ping-pong stops, never returns to ping-pong
- In some streams, download number changes
  - May represent current throughput
    745959 mean 74.5959 Mbps? So server can capture data if test aborts?
  - May represent something else
- Do not see close signal for stream
  - Client simply closes tcp-stream/socket to end transfer?
- Client only receives ABCDEFGHIJ from server
  - At least from this testserver (Acelx)

And that's all I know (at the moment).

So it seems to me it may be possible to connect to these testservers and get a long, 10s TCP stream (or several) and this would make your test more robust (by having 10s+ of duration).

Ookla claims this works up to several Gbps: http://blog.ookla.com/2011/06/16/breaking-the-1-gbps-barrier-over-cable/

Other option, I suppose, would be to download the random JPGs many times in parallel.
- Here you are at the mercy of the speedtest testserver's http server
- Run several captures, its bring your own http server
  - And also, bring your own PHP/ASP/JSP

Anyway an interesting thing. Very cool project, I'll use it in <200M locations. If you get bored and want to connect to the new Ookla servers, now you've got some data.

**Comment by taganaka** [comment]
Hello @zpeters, if you are interested, I just sketched my own speedtest.net cli version written in C++. It uses the new TCP raw protocol for all the metrics.

https://github.com/taganaka/SpeedTest

Here is the client: https://github.com/taganaka/SpeedTest/blob/master/SpeedTestClient.cpp
With the follow commands implemented:

`HI` <-- Simple handshaking
`PING <TS>` <-- Used for latency / best server selection / jitter calculation
`DOWNLOAD <BYTES>` <-- Download data
`UPLOAD <BYTES>` <--  Upload data 
`QUIT` <-- Simple quit

`PLOSS` <-- I'm working on it. It is used by http://www.pingtest.net/ to calculate packet loss. 

Cheers

**Comment by zpeters** [comment]
@taganaka gotta thank you for this info.  Much appreciate the share.  Good luck on your project.  I'd love to collaborate if either if us figure out anything cool in the future!

**Comment by zpeters** [comment]
Major themes will be 
- explore the binary protocol 
- reduce final exe size
- switch to a "command app" based approach instead of all of the switches
