### ISSUE TITLE
Investigate inaccuracy in speed reports

### ISSUE THREAD

**Issue by zpeters** [zpeters/speedtest#46]
Culley Morrow <cmorrow@mta-telco.com>
Oct 27

to me 
I ran across your CLI speedtest tool on the Kaseya forums and it definitely has some promise. Like others I am not sure about the reliability of the results. This is with the most current speedtest-32-v0.8.4-a-9-g8644fff.exe.
 
I am on a LAN within an ISP’s main office. The server I am testing against is about 20 miles away and has a 100 down, 50 up pipe to it which is shared with the rest of the building. The web version gets a faster result consistently.
 

Culley Morrow
Oct 28 (13 days ago)

to me 
I used the –l command to find server number 3571 which is in our main CO less than 20 miles away. It should be the same server which I chose in both web and CLI. I ran it again this morning and I see the same results. This is a hardwire connection where the only bottleneck is the Cisco routers with 100mbps between my office and the main backbone routers.
 
Culley Morrow
MTA Tech Express
Systems/Network Admin II
Phone: 907.761.2682
 
From: Zach Peters [mailto:zpeters@gmail.com] 
Sent: Tuesday, October 27, 2015 3:16 PM
To: Culley Morrow <cmorrow@mta-telco.com>
Subject: Re: Inaccurate speeds?

**Comment by zpeters** [comment]
I just put out a debug release that will add some extra info to the upload process.  Would you mind running this with the "-d --uo" switches (-d = debugging, --uo = upload only) a few times and we'll see if we can catch this in the act again.

http://media.thehelpfulhacker.net/index.php?dir=speedtest/v0.8.4-d-1-ga02d067/

Thank you!

**Comment by ross-w** [comment]
FWIW we have the opposite issue - we are getting speeds considerably higher than our internet connection is capable of.

For example, on a 100/100 fibre connection:
```
$ speedtest-mac-amd64-v0.8.4-d
github.com/zpeters/speedtest -- unofficial cli for speedtest.net
Server: 2169 - Melbourne (Internode)
2016/02/24 09:19:41 Testing download speed
..........
2016/02/24 09:20:00 Testing upload speed
.....
Ping (Lowest): 2.30 ms | Download (Max): 330.05 Mbps | Upload (Max): 522.93 Mbps
```
The web version reports 93 down, 89 up. 

Happy to run with debug switches but it includes information I'd rather not share in a public forum. Let me know how I can supply this publicly or if I can redact some of it without making it useless.

**Comment by zpeters** [comment]
Not a problem.  If you want to email them to me privately it's zpeters@gmail.com.

**Comment by zpeters** [comment]
Still trying to find the time to look at this

**Comment by zpeters** [comment]
Rather than chasing this down any further, im going to focus on the new (undocumented) binary protocol.  I believe this will both simplify things and lead to more accurate results.  There is too much "magic" in their current way of calculating the upload/download speed and it's probably a better payoff to focus on the new protocol for now.

Will reopen and reinvestigate if the binary protocol turns into a dead end.
