### ISSUE TITLE
Choose to test wired or wireless connection

### ISSUE THREAD

**Issue by igorissen** [zpeters/speedtest#54]
Hi,

I don't know if it is possible but can you add an option to choose between wired or wireless connection to make the speed test ?

Why do I want to choose wireless connection ? Just to tell my ISP (on Twitter) that their hardware is crappy.

**Comment by zpeters** [comment]
I'm not sure if this is possible to do but i will give it some thought

**Comment by jgysel** [comment]
I have a similar issue here. We have multiple ISP uplinks on several hosts for redundancy reasons. A flag for choosing the network interface would be great!

**Comment by zpeters** [comment]
It looks like in https://golang.org/pkg/net/ there are provisions for listing interfaces and selecting an interface when you make a tcp or udp connection.  I will have to look into this.

**Comment by jgysel** [comment]
@zpeters, that sounds good. I just found out that it is better if one binds to an IP (and not directly to an interface) as this gives more flexibility for complex host configurations.

**Comment by zpeters** [comment]
Started playing around with code to list available interfaces and ips.  Need to look into http roundtripper -> dialer to see how to select which one we are using

**Comment by zpeters** [comment]
https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779#.eu74467tj  here are some notes that will help

**Comment by zpeters** [comment]
Able to get a list of interfaces, but continue to get this when trying to select (and use) a particular interface.

2016/06/28 19:22:06 Get http://google.com: dial tcp 192.168.1.70/24->[2607:f8b0:4002:c07::8a]:80: mismatched local address type ip+net
