### ISSUE TITLE
Error on Exit

### ISSUE THREAD

**Issue by carylewis** [zpeters/speedtest#55]
I guess there has been a change to the cli package:

On exit, the speedtest program is outputting:

DEPRECATED Action signature.  Must be `cli.ActionFunc`.  This is an error in the application.  Please contact the distributor of this application if this is not you.  See https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

This can be fixed by adding a:

Os.Exit(0)

at the end of the runTest function

sorry, I'm not sure how to do a pull request...

**Comment by zpeters** [comment]
No worries, i'll take a look at this.

**Comment by zpeters** [comment]
All set.  updated in v0.8.6-a  Thanks for the report @carylewis

**Comment by carylewis** [comment]
You're welcome. I should have forced myself to learn to do the pull request. 

Do you know of any c/c++ implementations of speedtest?
