### ISSUE TITLE
Don't use "./" for local imports

### ISSUE THREAD

**Issue by vendion** [zpeters/speedtest#56]
Imports like `./debug` fail when fetching packages with `go get`.  Example:

```
[vendion@Baldr][~]% go get github.com/zpeters/speedtest
/home/vendion/gocode/src/github.com/zpeters/speedtest/speedtest.go:19:2: local import "./debug" in non-local package
```

Instead those imports should be defined as `github.com/zpeters/speedtest/debug` that way when a user runs `go get github.com/zpeters/speedtest` it will know where to fetch those other packages.  Another option if you don't need to support Go 1.4 or older you can make those other packages an "internal dependency" by creating an `internal` directory and moving the `debug`, `print`, `settings`, `sthttp`, `tests` under that directory then the import line can be changed to `speedtest/internal/debug` and so on.

Also small nitpick but instead of having multiple import statements in your source code, it is more idiomatic in Go to have one import statement and group standard lib packages, internal/vendored packages, and 3rd party packages separating them by a new line.  See the [Imports section of the Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#imports) page of the Go wiki for details.  It is recommended to install [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports) and either set your editor to run that on save or create a git hook that runs it when commiting changes or before pushing.  Goimports handles everything that `gofmt` does plus manages your `import` section adding new packages you use, and removing unused packages as well as correctly groups them.

**Comment by zpeters** [comment]
I really appreciate the feedback/corrections and will take a look at this very soon.  Thank you,

**Comment by zpeters** [comment]
https://github.com/zpeters/speedtest/releases/tag/v0.8.6-b

**Comment by zpeters** [comment]
not quite fixed

**Comment by polyzen** [comment]
Getting the following errors while trying to build v0.8.6-c with [this](https://ptpb.pw/Lvnd) Arch Linux PKGBUILD:

```
package speedtest/internal/debug: unrecognized import path "speedtest/internal/debug" (import path does not begin with hostname)
package speedtest/internal/print: unrecognized import path "speedtest/internal/print" (import path does not begin with hostname)
package speedtest/internal/settings: unrecognized import path "speedtest/internal/settings" (import path does not begin with hostname)
package speedtest/internal/sthttp: unrecognized import path "speedtest/internal/sthttp" (import path does not begin with hostname)
package speedtest/internal/tests: unrecognized import path "speedtest/internal/tests" (import path does not begin with hostname)
```

Any ideas?

**Comment by zpeters** [comment]
@polyzen thanks for bringing this up.  I was doing some work yesterday on reorganizing the internal functions and i thought i had everything working since it built locally just fine.  I noticed my travis ci build was failing but ran out of time to look into this.   v0.8.6-a was right before i introduced these changes. i'm going to try to work on getting this latest build working later today.  My fault for playing with something i still don't full understand

**Comment by zpeters** [comment]
@polyzen i've updated the develop branch with what i think will work.  Do you have any way to test your build process against the "develop" branch and see if that works?

**Comment by polyzen** [comment]
@zpeters, I don't see a way to change the branch used by `go get`.

**Comment by vendion** [comment]
@polyzen `go get` has special rules for that.  It first looks for a branch or tag that matches the Go version too build with.  So if a project was dropping support for Go 1.3 they can create a branch or tag called something like `go-1.3` (or something like that I forget exact rule) then when a user with Go 1.3 does `go get` that is the version that gets pulled ignoring the master branch.

The only thing that could be done is to manually clone the repo, checkout the `develop` branch and run `go install .`, because @zpeters went the internal route the repo will have to be cloned under `$GOPATH/src` so `$GOPATH/src/github.com/zpeters/speedtest` would work (and where `go get` would put it anyways).  If $GOPATH isn't setup then you need to see https://golang.org/doc/install#testing

**Comment by zpeters** [comment]
In the current dev branch i moved the "libraries" out to their own folders again and have set the import path to "github.com/zpeters/speedtest/FOO".  Doing that i was able to "go build" successfully.  I'll look this over more closely later and then merge it into master.  It sounds like that would fix your issues @polyzen ?

**Comment by vendion** [comment]
@zpeters If you want to go the route of having `internal` directory when I
have some spare cycles I would be more than happy to fork the repo set
everything up and submit a PR (I'll also add in a `PKGBUILD` file to use in
the AUR) when I have some spare cycles (probably won't be until this
weekend) so you can see how it works if you would like.

**Comment by polyzen** [comment]
> The only thing that could be done is to manually clone the repo, ...

Will do.

> I'll also add in a `PKGBUILD` file to use in the AUR

https://aur.archlinux.org/packages/speedtest-zpeters/ :)

**Comment by polyzen** [comment]
@vendion, sorry, very inexperienced with go. What should I be setting GOPATH to? I don't see any ~/.go dir or the like. Here's where I'm at: https://ptpb.pw/k8Y-

**Comment by vendion** [comment]
@polyzen You should create a directory that you want go to store all downloaded source code and place all compiled executables and packages.  One example would be to create a `$HOME/go` directory  and set the GOPATH to that.

```
mkdir $HOME/go
export GOPATH="$HOME/go"
export PATH="$PATH:$GOPATH/bin"
```

That will be enough to get you going, and when you do a `go get ...` the go toolchain will create _$GOPATH/bin_, _$GOPATH/pkg_, and _$GOPATH/src_.

>> I'll also add in a PKGBUILD file to use in the AUR

> https://aur.archlinux.org/packages/speedtest-zpeters/ :)

I'm aware that he already has it up in the AUR, but if @zpeters wants to go the 1.5+ route of managing his internal packages like `speedtest/internal/FOO` then a `GOPATH` will need to be setup in the PKGBUILD for users that don't already have one set, then the binary will need to be moved from `$srcdir/$GOPATH/bin/speedtest` to `$pkgdir/usr/bin/speedtest` during the `package()` function of the PKGBUILD.  I was offering to write up an example to give @zpeters something to go off or just use and call it a day ;)

**Comment by zpeters** [comment]
@vendion I would be grateful for any pulls you want to do.  Still very much trying to stumble through this.  I really appreciate all of your help and guidance!

**Comment by polyzen** [comment]
Am I missing something? :p https://ptpb.pw/Cp3e

**Comment by vendion** [comment]
@polyzen Yeah the source code isn't in the correct place.  You should put it in _$GOPATH/src/github.com/zpeters/speedtest_ then you can cd into that directory and run `go install` and it will build the binary and place it in _$GOPATH/bin_ for you.

FYI: #64 should resolve the issue so you should just be able to just run `go get -u github.com/zpeters/speedtest` and everything will work as expected.  _Note_: The `-u` flag tells `go get` to pull the latest commit from the source repo if the package had been pull before.

I say _should_ as a CMA, because while I tested it on my system running go version go1.6.2 darwin/amd64 if you have Go 1.4 or below installed it won't work, and if you have Go 1.5 installed then you need to set `GO15VENDOREXPERIMENT=1` in your $SHELL configuration file (.bashrc, .bash_profile, .zshrc, etc).  With Go 1.6 and above everything will just work.

**Comment by polyzen** [comment]
@vendion, sorry never took the time to try that. Thanks again. :)

I know this is closed already, but just confirming the previous errors are gone with 0.8.7. :)

**Comment by polyzen** [comment]
@vendion, didn't have to change the PKGBUILD for 0.8.7, but any improvements are welcome.
