### ISSUE TITLE
log recommendation

### ISSUE THREAD

**Issue by zpeters** [zpeters/speedtest#71]
@bkearan

  Perhaps you could put in an option to output/log to file?  Doing >c:\temp\speedtest.txt worked, but maybe some kind of -f (also log to file) option would be better? Or even just have the –r option include a report file.  And a –ra option to append to the report, to develop a history in order to see patterns, such as time of day it slows down, etc.

**Comment by ccmgtech** [comment]
Creating a true .csv file would be great. Right now, I am using -rc "," option to use a comma as my delimiter. This does work, however many of the server name/locations have commas in them which causes each occurrence of a comma to create a seperate column when imported int MS Excel.  Here is an example: Quonix, Inc.(Philadelphia, PA,United States).  It would be nice to have the server name field exported in quote marks to avoid this issue or perhaps just replace commas with spaces.

**Comment by zpeters** [comment]
I fixed this so the server field is printed correctly (with quotes).  Also discovered and fixed a bug where the banner was showing in "report" mode.  I turned it off so you can just pipe directly to a csv file.  New release is v1.0.3-a

**Comment by ccmgtech** [comment]
Adding the quotes did work thank you.  Unfortunately, with version 1.0.3-a the download and upload speeds are way off as compared to v 1.0.2-b   For example, if i run the test with 1.0.2-b it shows ping 35.02ms, Download 52.82 Mbps, Upload 28.58Mbps.   If i run it with 1.0.3-a, it shows ping 33.02ms, Download 28.66Mbps, Upload 0.41  (zero . 41)    I have run both versions, multiple times in a row, with similar results.  1.0.3-a is always way off.  Note that i am using the same testing server id of 1769 for each test in both versions.   If i run the tests with no server specified it also comes back with similar results (v1.0.3-a being way lower values) I have attached a screen shot of my tests for your review. Thank you!
![kentgerhartvalues](https://cloud.githubusercontent.com/assets/23266327/20069121/468ab418-a4e9-11e6-804a-18d6b9327273.jpg)

**Comment by zpeters** [comment]
thank you for the heads up i will do some investigation.  I can't say right off hand what all code changed between versions so i'll need to do some digging. 

I see you are using labtech.  Curious how you are using it, we are just getting into Labtech where i work so i'm interested in how you speedtest into the system.  Drop me a line at zpeters@gmail.com
