### ISSUE TITLE
cleaner split between libraries and interface

### ISSUE THREAD

**Issue by zpeters** [zpeters/speedtest#77]

**Comment by iamacarpet** [comment]
@zpeters, love the direction of allowing use as a library.

I had previously integrated this into a project but pretty much had to re-write it to make it integrate, with the negative effect that now I need your updates, it would be a lot of changes again.

Now, it looks a lot more suitable to integrate as-is - only thing is it currently dies on error, but for a long running program, I would need a library to return errors from the functions.

If I create a pull request for this, would you be open to accepting it?

**Comment by weineran** [comment]
I am working on two network measurement projects at Northwestern, both of which would also be interested in using this project as a library.  I can try to help with the refactor if this is something you want to pursue.

**Comment by zpeters** [comment]
I would absolutely be open and welcoming to efforts to clean up the code.  if you don't mind can you send me your contact info to zpeters@gmail.com to coordinate.

**Comment by zpeters** [comment]
The biggest problem plaguing the project right now is the sometimes random inaccuracies.  Going through the exercise of cleaning up the code might root out some of these bugs, or at least make them easier to see.

**Comment by zpeters** [comment]
I haven't played with this yet but i noticed that there is a "Projects" feature.  I created a project for this effort of splitting up the code into a library and frontend.  I figured that would be a good place to collect all of our thoughts, examples of good code and techniques, etc for the future work.

https://github.com/zpeters/speedtest/projects/2
