### ISSUE TITLE
Blacklist servers

### ISSUE THREAD

**Issue by ccustine** [zpeters/speedtest#79]
I have found several ISP provided servers which don't respond to any requests (either icmp or http) from outside of the ISP subnets.   A speedtest from my office resolves to one of these servers even though I am on a different ISP, so my tests hang on the latency test. I suspect that the Ookla tests have some way of knowing which servers do this.

If there is no known flag in the server listing to use to skip these servers, I think a blacklist in a config file or at least a command line option to ignore certain server ids would be helpful.

The server I encounter daily is:
Longmont, CO United States US LPC NextLight 6285

**Comment by zpeters** [comment]
This definitely sounds like something that can be worked around.  I will take a look at this.

**Comment by zpeters** [comment]
I've got a testing build up here.  Added a switch "-b" or "--blacklist" that takes either a single server number

speedtest -b 1234

or a comma separated list

speedtest -b "1234, 4321, 1111"

Let me know how this works for you, then we can figure out if a switch is the best way to go or if we should do this through a config file or some other means

http://media.thehelpfulhacker.net/index.php?dir=speedtest/v1.0.1-3-g1f4e925/

**Comment by ccustine** [comment]
This works great for me. I am using an alias with the blacklist option so that it always works for me, so I am not sure if it is worth it for you to add an entire feature to read from a persistent option config file just for this. Maybe if there become other reasons for doing that, but I wouldn't bother to do it just for this.

Thanks for adding this!

**Comment by zpeters** [comment]
No worries, glad it worked.  I'll do some work this week on adding this feature into the main code.  Thanks for testing!

**Comment by zpeters** [comment]
Released v1.0.2-a
