### ISSUE TITLE
version doesn't print the version

### ISSUE THREAD

**Issue by ddurdle** [zpeters/speedtest#80]
using https://github.com/zpeters/speedtest/releases/download/v1.0.0/speedtest-linux-arm-v1.0.0

~ $ ./speedtest-linux-arm-v1.0.0 -v
speedtest version 
~ $ ./speedtest-linux-arm-v1.0.0 -version
speedtest version 
~ $

**Comment by zpeters** [comment]
Added after v1.0.0 .. will post new binaries

**Comment by polyzen** [comment]
This appears to still be an issue.

**Comment by ddurdle** [comment]
Oh, yes, true

/u01/speedtest $ ./speedtest-linux-arm-v.1.0.1 -v              
speedtest version 
/u01/speedtest $
