### ISSUE TITLE
Interface value missing

### ISSUE THREAD

**Issue by ddurdle** [zpeters/speedtest#81]
README indicates there should be an interface value parameter but 1.0.0 doesn't accept it.

"   --interface value, -I value     Source IP address or name of an interface"
GLOBAL OPTIONS:
   --algo value, -a value          Specify the measurement method to use ('max', 'avg')
   --debug, -d                     Turn on debugging
   --list, -l                      List available servers
   --update, -u                    Check for a new version of speedtest
   --ping, -p                      Ping only mode
   --quiet, -q                     Quiet mode
   --report, -r                    Reporting mode output, minimal output with '|' for separators, use '--rc' to change separator characters. Reports the following: Server ID, Server Name (Location), Ping time in ms, Download speed in kbps, Upload speed in kbps
   --downloadonly, --do            Only perform download test
   --uploadonly, --uo              Only perform upload test
   --reportchar value, --rc value  Set the report separator. Example: --rc=','
   --server value, -s value        Use a specific server
   --mini value, -m value          URL of speedtest mini server
   --numclosest value, --nc value  Number of 'closest' servers to find (default: 3)
   --numlatency value, --nl value  Number of latency tests to perform (default: 5)
   --help, -h                      show help
   --version, -v                   print the version

**Comment by zpeters** [comment]
Added after v1.0.0 .. will post new binaries

**Comment by ddurdle** [comment]
Tested in 1.0.1 and working well on a system with two different gateways and three different source IPs.
