### ISSUE TITLE
Make instructions in readme

### ISSUE THREAD

**Issue by ddurdle** [zpeters/speedtest#82]
Make instructions in readme would be appreciated.  Never used "go" and having lots of compiling issue as I have no idea how to install the undocumented dependencies.

go build -ldflags="-X main.Version=v1.0.0-3-g4f33929" -o bin/speedtest
speedtest.go:18:2: cannot find package "github.com/dchest/uniuri" in any of:
	/usr/lib/go/src/pkg/github.com/dchest/uniuri (from $GOROOT)
	($GOPATH not set)
speedtest.go:23:2: cannot find package "github.com/google/go-github/github" in any of:
	/usr/lib/go/src/pkg/github.com/google/go-github/github (from $GOROOT)
	($GOPATH not set)
speedtest.go:24:2: cannot find package "github.com/spf13/viper" in any of:
	/usr/lib/go/src/pkg/github.com/spf13/viper (from $GOROOT)
	($GOPATH not set)
speedtest.go:25:2: cannot find package "github.com/urfave/cli" in any of:
	/usr/lib/go/src/pkg/github.com/urfave/cli (from $GOROOT)
	($GOPATH not set)
speedtest.go:19:2: cannot find package "github.com/zpeters/speedtest/internal/print" in any of:
	/usr/lib/go/src/pkg/github.com/zpeters/speedtest/internal/print (from $GOROOT)
	($GOPATH not set)
speedtest.go:20:2: cannot find package "github.com/zpeters/speedtest/internal/sthttp" in any of:
	/usr/lib/go/src/pkg/github.com/zpeters/speedtest/internal/sthttp (from $GOROOT)
	($GOPATH not set)
speedtest.go:21:2: cannot find package "github.com/zpeters/speedtest/internal/tests" in any of:
	/usr/lib/go/src/pkg/github.com/zpeters/speedtest/internal/tests (from $GOROOT)
	($GOPATH not set)
Makefile:14: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by ddurdle** [comment]
Readme suggests 0.8.6.  See screenshot.

![image](https://cloud.githubusercontent.com/assets/851508/17459962/660696fe-5c1e-11e6-8f3c-7ec8b621595f.png)

**Comment by zpeters** [comment]
Updated readme.

I'll add instructions for building from source soon.

Generally you'll need to have "go" installed as well as "glide" (https://github.com/Masterminds/glide).  Glide is the package manager.  Once that is installed you should be able to do something like "glide up" to pull all of your dependencies and then "go build" to build the exe.

Thanks for the issues, much appreciated

**Comment by zpeters** [comment]
Added info to the wiki on building

**Comment by polyzen** [comment]
[This build script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=speedtest-zpeters) still appears to be working. Would there be an issue if it's kept as-is, or should I match these instructions?

**Comment by zpeters** [comment]
if the build script is working i may have misspoken in the instructions (it's been a long week).  let me review and get back with you.

Thanks for bringing this up.

**Comment by zpeters** [comment]
Confirmed that "go get github.com/zpeters/speedtest" is all that is needed to generate the binary.  Keeping this issue open to remind me to study how glide works and update the Wiki

**Comment by zpeters** [comment]
Updated wiki
