### ISSUE TITLE
Discrepancy between CLI and website?

### ISSUE THREAD

**Issue by WAdama** [zpeters/speedtest#85]
Since the change on Speedtest.net and and the last CLI I have discrepancies between the measurements.

The website states round about 100 MBit/s download and the CLI is about 10-15 MBit under this (85 to 90 MBit/s). The upload is also lower. The ping is more than doubled.

By chance I tested an older version I've had on one of my drives. It works without the config error and showed the same amount in down and upload. I tried other older version and got up to version 0.8.6-c.

**Comment by zpeters** [comment]
Much appreciated , i will look into this.

**Comment by zpeters** [comment]
Can you checkout a few things for me: 
- check out the latest build v1.0.2-c and run a few tests in a row (three or so) using the same server (specify it's server number with the "-s" flag).  Let me know what the consistency looks like there
- test against a few alternate speed testing sites and see how that compares.  I don't have a lot of faith in the speedtest.net website for accurate speed measurements.  I like: https://www.speakeasy.net/speedtest/  and http://testmy.net/.

Let me know what these speeds all look like in comparison.

**Comment by WAdama** [comment]
Of course:
speedtest version v1.0.2-c
2016-09-01 12:05:02 +0200|7562|LWLcom GmbH(Hamburg,Germany)|43.15|92309|5715
2016-09-01 12:05:27 +0200|7562|LWLcom GmbH(Hamburg,Germany)|50.85|96355|5674
2016-09-01 12:06:08 +0200|7562|LWLcom GmbH(Hamburg,Germany)|50.77|94420|5761

Funny again the old version:
speedtest version v0.8.6-c
2016-09-01 12:01:27 +0200|7562|LWLcom GmbH(Hamburg,Germany)|17.81|100373|6315

Speakeasy I can't reach, testmy.net seconds more the new one. Other tests I have had a look on shows round about 100 MBits, some less.

I have also an one liner in powershell, which runs a test download of a file from Akamai:
"{0:N2} Mbit/sec" -f ((10/(Measure-Command {Invoke-WebRequest 'http://client.akamai.com/install/test-objects/10MB.bin'|Out-Null}).TotalSeconds)*8)

Speed differs from 65 to 100 MBits...

You can at least say, it's not an easy subject.

**Comment by plambrechtsen** [comment]
I have a similar issue. This instance of the speedtest-cli works at half the speed approximately of the python speedtest-cli https://github.com/sivel/speedtest-cli and that can have wildly different results at high speed. Testing on a 1000/500Mbit internet connection on the browser or using the Android speedtest app I get 930/460Mbit. Using the python speedtest-cli I get 730/160 or so and CPU pegs at 100% for that thread. With go speedtest-cli I get 350/52.

**Comment by ramses147** [comment]
Same problem on the speedtest.net website:
download 20.81 and upload 1.60

on the CLI with all versions: 
speedtest-32-v1.0.3-a.exe -s 2872
download: 6.29
upload: 0.4 
!!!

**Comment by zpeters** [comment]
Please follow #94
