### ISSUE TITLE
Internal package not allowed

### ISSUE THREAD

**Issue by nlamirault** [zpeters/speedtest#87]
Hi i try to use speedtest as a library for a project.
I can't use sthttp package : 

```bash
imports github.com/zpeters/speedtest/internal/sthttp: use of internal package not allowed
```
Do you think it is possible to refactor code without internal ?
Thanks.

**Comment by zpeters** [comment]
Definitely open to this but i don't have a lot of time lately.  I'll keep this bug open and look at it when i have time.

Thank you,

**Comment by nlamirault** [comment]
See #88

**Comment by zpeters** [comment]
Dude awesome thank you.  Sorry there will be a slight delay but ill try to look over the merge in the next few days.  Thanks!

**Comment by zpeters** [comment]
merged pr 88 and 89

**Comment by zpeters** [comment]
I noticed today that something in one of these patches broke a few things.  it looks like the http timeouts aren't working and i think that is why it is randomly failing for some people.  Also blacklisting isn't working .   I tried to revert the PR's but i was only able to revert one.  @nlamirault lamirault can you look at this?

**Comment by nlamirault** [comment]
OK. I try to fix that.

**Comment by nlamirault** [comment]
Strange. I try some logs : 

```go
log.Printf("Keys: %s", viper.AllKeys())
log.Printf("Blacklist: %s", viper.GetString("blacklist"))
```

and : 
```
$ bin/speedtest-v1.0.2-c-8-ga232615 -d -b http://paris1.speedtest.orange.fr/upload.php
2016/10/17 17:29:35 Keys: [numlatencytests algotype report httpdownloadtimeout ulsizes blacklist speedtestconfigurl numclosest reportchar httpconfigtimeout speedtestserversurl quiet httplatencytimeout dlsizes debug]
2016/10/17 17:29:35 Blacklist: 
2016/10/17 17:29:35 STClient: &sthttp.SpeedtestConfig{ConfigURL:"http://c.speedtest.net/speedtest-config.php?x=jgkIV7zvY5LZHhWB", ServersURL:"http://c.speedtest.net/speedtest-servers-static.php?x=9anLuNni9qiLXnWR", AlgoType:"max", NumClosest:3, NumLatencyTests:5, Interface:"", Blacklist:""}
```

**Comment by zpeters** [comment]
try using a number for the black list parameter.  you can get the server
number by first running speedtest -l

**Comment by nlamirault** [comment]
I try that : 

```bash
$ bin/speedtest-v1.0.2-c-8-ga232615 -l|grep France
1563 | myplex.org (Gravelines, France)
...
4036 | TestDebit.info (Marseille, France)
4020 | Old-Linux.com (Perpignan, France)
bin/speedtest-v1.0.2-c-8-ga232615 -d -b 4020
2016/10/18 09:22:10 Keys: [algotype httpdownloadtimeout numclosest dlsizes quiet httplatencytimeout numlatencytests httpconfigtimeout ulsizes debug blacklist reportchar speedtestconfigur
l report speedtestserversurl]
2016/10/18 09:22:10 Blacklist: 
2016/10/18 09:22:10 STClient: &sthttp.SpeedtestConfig{ConfigURL:"http://c.speedtest.net/speedtest-config.php?x=DGXXHo6DRiSYLQno", ServersURL:"http://c.speedtest.net/speedtest-servers-sta
tic.php?x=6XEUrCVk1ze1qKUQ", AlgoType:"max", NumClosest:3, NumLatencyTests:5, Interface:"", Blacklist:""}
```

Any idea ?

**Comment by zpeters** [comment]
i will look some more tonight.  Which commit are you working off ?

On Tue, Oct 18, 2016 at 2:24 AM, Nicolas Lamirault <notifications@github.com

**Comment by nlamirault** [comment]
from my PR

**Comment by zpeters** [comment]
@nlamirault i made a little progress.  It looks like we were overwriting the setting of blacklist in speedtest.go.  once i removed the initializing line from the struct it will now read in a blacklist value.  The problem now is its only reading in the first value if i specify "123, 234, 345" it will only get "123,".  Can you see a way to bring in the full string?

Here is the diff

https://gist.github.com/zpeters/8882312321ebb26877fd93bfa2c1e102

**Comment by zpeters** [comment]
Tentatively fixed w/ dev 6cba4afe5e286586ae04ae3aedd88a84ab7ee542

**Comment by zpeters** [comment]
I believe some of the blacklisting issues, timeout issues and a few other things have been resolved in this development release.  Please let me know how this looks.  If everything seems stable i'll push this to the main branch next week.

https://github.com/zpeters/speedtest/releases/tag/v1.0.2-c-fixes

Thank you

**Comment by nlamirault** [comment]
Great ! Congrats
