### ISSUE TITLE
Upload results are limited to ~1 MBps

### ISSUE THREAD

**Issue by polyzen** [zpeters/speedtest#94]
Upload results are limited to ~1 MBps, apparently starting with 1f11697cc057ec833bbd7e15b7519210aa05fe55. Tested 1.0.3-a on 3 separate systems (2 in the same network and the other done by an associate).

Didn't catch this earlier as it turns out I was upgrading improperly. The `-u` option was needed for `go get`. From `go get -help`:
> The -u flag instructs get to use the network to update the named packages and their dependencies. By default, get uses the network to check out missing packages but does not use it to look for updates to existing packages.

**Comment by zpeters** [comment]
Interesting, i will take a look

**Comment by zpeters** [comment]
Trying to work on this but i'm struggling with a terrible internet connection.   If you go back to the release v1.0.2-c-fixes does that have more normal speed?

https://github.com/zpeters/speedtest/releases/tag/v1.0.2-c-fixes

**Comment by polyzen** [comment]
1.0.2-c

**Comment by zpeters** [comment]
If anyone is able to test i just committed an update to dev (7d194d0) and have some binaries here.  My internet connection is crap so i can't do any good testing at the moment.  I expect the speeds to be off a little, but not but the magnitude we were seeing...

http://media.thehelpfulhacker.net/index.php?dir=speedtest/v1.0.3-a-2-testing/

**Comment by polyzen** [comment]
Thank you, that does it. 👍
