### ISSUE TITLE
Download speedtest results show half speed

### ISSUE THREAD

**Issue by dmacias72** [zpeters/speedtest#97]
Versions above v1.0.2-c the download speed result is half of what previous versions show. I have tried all versions from v1.0.2-c-fixes to 'Emergency Fix - speed issues' with the same result. The last version that gives the correct speed for me is v1.0.2-c. I'm using the linux-amd64 on Slackware 14.2 (server), Linux Mint 18.1 (laptop) and Ubuntu 16.04 (virtual machine).

**Comment by zpeters** [comment]
Thank you for reporting.  i will review sometime this week

**Comment by dmacias72** [comment]
Also I noticed I've been getting some upload spikes. My connection is about 120 down and 6 up but I get random upload spikes of 300.

**Comment by zpeters** [comment]
Just curious if anyone is still seeing this same issue and if changing servers has mad any difference?

I've got a few cron jobs setup to do a speedtest on a few different servers and save it into a graph.  Looking over the course of a few days i'm seeing something interesting.  In this example the traffic to Tokyo is relatively consistent, but the traffic to Chicago has spikes at different times.

<img width="1278" alt="screen shot 2017-01-19 at 12 03 54 pm" src="https://cloud.githubusercontent.com/assets/39647/22119056/ac5cbe32-de3f-11e6-9d6d-1de6ab0b854d.png">

**Comment by nemchik** [comment]
![Imgur](http://i.imgur.com/p1wH6dM.png)
Definitely feel like there is a difference, but I have not tested enough to provide true conclusive data. 

Earlier today I was trying to test the difference between the CLI and speedtest.net in a browser and of course those ressults are different (intentionally), but I think I may have stumbled on an issue. I have a client with a 90 mbps download speed and whenever I try using the 'Emergency Fix - speed issues' version it tells me they have an 8 mbps connection (less than 10x what they actually have). Test results on speedtest.net do reflect the 90 mbps correctly, but I know those results will differ from the CLI. So I'm wondering if the CLI is consistently trying to test a very small file and thus completing the test on that connection so fast that it reports ~8 mbps because it's downloaded the entirety of the test in under 1 second?

That may be a different issue, but it's what lead me to do the testing, and lead me here to this issue.

**Comment by zpeters** [comment]
Thanks for the report. I have been rather tied up lately so haven't dug in too much. This info should help me with my research into the issues.  

A Big thanks to everyone who's been supplying reports and data to help figure this out

**Comment by nemchik** [comment]
![Imgur](http://i.imgur.com/UaRnZCE.png)
Here by the way is a set of results from the 90 mbps connection I had mentioned earlier. In this screenshot I have the latest "emergency fixes" build named speedtest.exe and I have 1.0.2-c named accordingly. There is definitely a difference in speed. I would not say half, but significant.

**Comment by nemchik** [comment]
P.S. I would also like to point out that the results I get are consistent from any single build. For example if I stick with Emergency Fixes and test 10 times in a row the results are expectedly consistent, and the same for any other build. I only see this difference when switching between builds older/newer than 1.0.2-c (so far).

**Comment by zpeters** [comment]
I've created a project to try to break up some of the work and document the issues around the speed testing. I'm hoping this will help to keep organized and encourage others to jump in with ideas w/o cluttering up the ticket.

https://github.com/zpeters/speedtest/projects/1

**Comment by buzurk** [comment]
I am experiencing the same issue using the latest speedtest-64-speed-issues.exe

Navigating to the website consistently yields me about 98mbps down and 39mb/s up which is consistent to my 100mbps down and 40mbps up connection

using the script, i never seem to get over 65mb/s down and 20mbps up

Hoping for a solution.

**Comment by zpeters** [comment]
Thank you.  I've been trying with this on and off and not getting any good results.  I'm pretty close to just starting from scratch on this one.  Sorry it's been a long delay on getting updates on this.

**Comment by zpeters** [comment]
I may look at this again but i'm at a point where i can't really devote any time to this.  It looks like they are working on moving to a "beta" site that will use an entirely different scheme.  For now i will accept any pull requests but i dont' have time to devote to working on this anymore.

**Comment by ipsecguy** [comment]
Hi, just to add to that: the speedtest-cli python script delivers different (and results mor in line with the speedtest website).

I have a 100dn/40up connection and the command line tools measures 92.74/36.49/6.8ms and chooses the server hosted of my ISP.

This software here measures 80/32.3/12.37ms and chooses servers seemingly randomly. Even why I force it to use the server (1746, Vodafone DE) I get even lower value (75/28).

So something systematic is different, I expected the python version to be slower than C/Go and thus expected it to be more inaccurate.

I came here to replace the python version and collectd with the Prometheus exporter of nlamirault.

**Comment by zpeters** [comment]
Thank you for the feedback.  I will look over the speedtest-cli python script and see if there is anything i can learn.

thanks!

**Comment by zpeters** [comment]
COMING SOON
=============
This version of speedtest is not supported.  The underlying method of speed testing is not (and has not) been reliable.  There is a new version of the speedtest protocol that i am actively working on a rewrite for. Expected release date is September 2018

**Comment by zpeters** [comment]
Initial testing release of v2.0 is out for the testing. See "releases" for downloads.  The current "test" is hard coded and there are no options at the moment.  I believe we'll end up needing a "tuning" to adjust the size and amount of data based on your internet connection.  Please send me any feedback at zpeters@gmail.com or through the issues

**Comment by polyzen** [comment]
2.0.0-a:
```
Download results: 581.504907 mbps
Upload results: 281.828571 mbps
```

Official client:
```
Download: 126.14 Mbit/s
Upload: 133.78 Mbit/s
```

With a 150 Mbps connection.

**Comment by zpeters** [comment]
@polyzen that is helpful info thank you

**Comment by zpeters** [comment]
Merging into #111
